name: "[Encounters] - Invalid Data"
description: File an invalid or missing data report
title: "[Bug]: Invalid/Missing Data"
labels: ["splinters/encounter-data", "invalid/missing data"]
projects: ["exile-watch/splinters"]
assignees:
  - sbsrnt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/exile-watch/issues/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true