name: "📄 [Encounters] - Invalid Data"
description: File an invalid or missing data report
title: "Replace this text with this format: {map} - {encounter} - {ability}"
labels: ["nucleus/encounter-data", "invalid/missing data"]
projects: ["exile-watch/nucleus"]
assignees:
  - sbsrnt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!
  - type: input
    id: url
    attributes:
      label: exile.watch link
      description: Share the exile.watch url link where the bug is present
      placeholder: ex. https://www.exile.watch/encounters/endgame-bosses/sirus-awakener-of-worlds
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.exile.watch/legal/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true